### ISSUE TITLE
反馈个bug

### ISSUE THREAD

**Issue by RiverHorseLee** [striter/Unity3D-ToolChain_StriteR#1]
首先. 感谢分享.  
我在白嫖途中发现个bug.  反馈一下. 
UIMesh.cs 的 72行.  
Vector3 normal = normals[i].normalized;

目前此处的normals是按面重新计算的normal.  应该是取mesh上的normal才对.  不然会和shader上构造tbn时不一致

**Comment by striter** [comment]
迟来的回复.
根据需求决定是 原mesh法线 or 根据triangle生成的法线.
大概这边的版本比较简陋.
需要做一些简单的修改.

具体塞到模型的normal/tangent/color or 其他通道 则也根据需求来.
对应的其他通道的读取要做一些切线空间处理.
也许代码里遗漏了既需要根据triangle重新生成法线,又需要塞到其他通道里的情况.
